model:
  checkpoint: ./pretrained_models/pretrained_diffusion.pt

sample:
  seed: 0
  num_samples: -1
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  inv_temp: 1
  reverse_method: "SDE"
  sample_num_atoms: fixed
  num_atoms_to_sample: -1

